sudo: required
env:
  - PATH=/usr/lib:/lib
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - git clone https://github.com/traildb/traildb traildb-core && cd traildb-core
  - sudo apt-get install libjudy-dev libarchive-dev pkg-config build-essential
  - ./waf configure
  - ./waf build
  - sudo ./waf install
  - cd ..
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python test/test.py
